- name: Run docker compose
  hosts: all
  become: true
  tasks:
    - name: Ensure dev folder exists
      ansible.builtin.file:
        path: /home/ubuntu/app
        state: directory
        mode: "0755"

    - name: Copy compose yml
      ansible.builtin.copy:
        src: ./compose.yml
        dest: /home/ubuntu/app/compose.yml
        mode: "0644"
      notify: Restart docker compose

    - name: Pull latest docker images
      ansible.builtin.command:
        cmd: docker-compose pull
        chdir: /home/ubuntu/app
      when: ansible_os_family == 'Debian'

    - name: Create env file
      ansible.builtin.copy:
        dest: /home/ubuntu/app/.env
        content: |
          VITE_API_URL=http://{{ ip_address }}:8080/todos/

    - name: Run docker compose
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: /home/ubuntu/app
      when: ansible_os_family == 'Debian'

  handlers:
    - name: Restart docker compose
      ansible.builtin.command:
        cmd: docker-compose up --env-file /.env -d
        chdir: /home/ubuntu/app
      when: ansible_os_family == 'Debian'
